<!DOCTYPE html>
<html ng-app="haganeApp">
<head>
	<meta charset="UTF-8">
	<base href="<?= $this->config['document_root']; ?>">
	<script type="text/javascript">userId = <?=$this->auth->isAuth()?>;</script>
	<link type="text/css" rel="stylesheet" href="css/style.css"	media="screen,projection" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc1/angular-material.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

	<title>Biin Solutions</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

	<?=$this->loadJS('Angular/lib/angular.min.js')?>
	<?=$this->loadJS('Angular/lib/angular-animate.min.js')?>
	<?=$this->loadJS('Angular/lib/angular-aria.min.js')?>
	<?=$this->loadJS('Angular/lib/angular-material-rc-4.js')?>
	<?=$this->loadJS('Angular/app/haganeApp.js')?>
	<?=$this->loadJS('Angular/app/Config.js')?>
	<?=$this->loadJS('Angular/app/MainController.js')?>
	<?=$this->loadJS('Angular/app/AdminController.js')?>
	<?=$this->loadJS('Angular/app/ClienteController.js')?>
</head>
<body ng-controller="MainController">
<style>
.md-button {
	margin: 0;
}
.loader {
	position: absolute;
	top: 50%;
	left: 50%;
	z-index: 1000;
}
.slider {
	width: 100%;
}
</style>
<section layout="row" flex>
	<md-sidenav class="md-sidenav-left md-whiteframe-z2" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')">
		<md-toolbar class="md-primary">
			<h1 class="md-toolbar-tools">Biin Solutions</h1>
		</md-toolbar>
		<md-content layout-padding ng-controller="LeftCtrl">
		<md-list>
				<?php if($this->auth->isAuth()) :
				$obj= $this->user->getUserObject();
				if ($this->user->getUserType() == 'Administrador'): ?>
					<img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
					<p> Administrador <br><br> <?=$this->user->getNombreCompleto()?> </p>
						<md-list-item ng-class="{active : isActive('/Admin/index')}" ng-href="Admin/index">Inicio</md-list-item>
						<md-list-item ng-class="{active : isActive('/Admin/users')}" ng-href="Admin/users">Gesti&oacute;n de usuarios</md-list-item>
						<md-list-item ng-class="{active : isActive('/Admin/clientes')}" ng-href="Admin/clientes">Clientes</md-list-item>
						<md-list-item ng-class="{active : isActive('#')}" ng-href="#">Reporte de Clientes</md-list-item>
						<md-list-item ng-class="{active : isActive('/User/logout')}" ng-href="User/logout">Cerrar Sesion</md-list-item>
				<?php elseif ($this->user->getUserType() == 'Cliente'): ?>
					<img class="img-sidebar" src="<?=$this->getSecureImage($this->user->getImgPath()); ?>">
						<?=$this->user->getUserObject()->getEmpresa()?>
						<br><b> <?=$this->user->getNombreCompleto()?> </b>
						<md-list-item ng-class="{active : isActive('/Cliente/index')}" ng-href="Cliente/index">Inicio</md-list-item>
						<md-list-item ng-class="{active : isActive('/Cliente/dashboard')}" ng-href="Cliente/dashboard">Dashboard</md-list-item>
						<md-list-item ng-class="{active : isActive('/Cliente/subir')}" ng-href="Cliente/subir">Subir archivo</md-list-item>
						<md-list-item ng-class="{active : isActive('/Cliente/config')}" ng-href="Cliente/config">Configuración</md-list-item>
						<md-list-item ng-class="{active : isActive('/User/logout')}" ng-href="User/logout">Cerrar Sesion</md-list-item>
				<?php endif; ?>
				<?php else : ?>
						<md-list-item ng-class="{active : isActive('/User')}" ng-href="User" class="md-primary">Login</md-list-item>
				<?php endif; ?>
			</md-list>
		</md-content>
	</md-sidenav>

<section layout="column" flex>
	<md-toolbar>
		<div class="md-toolbar-tools">
			<md-button ng-click="toggleLeft()" hide-gt-md class="md-icon-button">
				<md-icon md-font-set="material-icons">menu</md-icon>
			</md-button>
			<h2>{{toolbar_title}}</h2>
			<span flex></span>
			<md-button class="md-icon-button" aria-label="Contextual" ng-click="toggleRight()" ng-hide="isOpenRight()">
				<md-icon md-font-set="material-icons">more_vert</md-icon>
			</md-button>
		</div>
	</md-toolbar>


	<md-content flex style="padding: 15px;">
		<div class="loader">
			<md-progress-circular md-mode="{{loading}}"></md-progress-circular>
		</div>
		<?php echo $this->view; ?>
	</md-content>


</section>
	<md-sidenav class="md-sidenav-right md-whiteframe-z2" md-component-id="right">
		<md-toolbar class="md-accent">
			<h1 class="md-toolbar-tools">Menu contextual</h1>
		</md-toolbar>
		<md-content ng-controller="RightCtrl" layout-padding>
			<form>
				<md-input-container>
					<label for="testInput">Test input</label>
					<input type="text" id="testInput" ng-model="data" md-autofocus>
				</md-input-container>
			</form>
			<md-button ng-click="close()" class="md-primary">
				Close Sidenav Right
			</md-button>
		</md-content>
	</md-sidenav>
</section>
</body>
</html>
