<?php if ($this->auth->isAuth()) : ?>
	<a  href="/User/logout">Logout</a>
ya etsas logueado tututruur   shhhoohh
<?php else: ?>
<form action="/User/auth" method="post">
	<md-input-container >
		<label>User</label>
		<input name="user" type="text" ng-required="true">
	</md-input-container>
	<md-input-container >
		<label>Password</label>
		<input name="password" type="password" ng-required="true">
	</md-input-container>
	<md-input-container >
		<md-button type="submit">Entrar</md-button>
	</md-input-container>
</form>
<?php endif; ?>