<section id="pagecontent" layout="row" layout-sm="column" flex>
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
		<h2 class="md-title">Login</h2>
		<md-subheader class="md-warn">Usuario inactivo.</md-subheader>
		<form action="User/auth" method="post">
			<md-input-container >
				<label>User</label>
				<input name="user" type="text" ng-required="true">
			</md-input-container>
			<md-input-container >
				<label>Password</label>
				<input name="password" type="password" ng-required="true">
			</md-input-container>
			<md-button style="min-width: 150px; float: right;" class="md-primary md-raised" type="submit">Entrar</md-button>
		</form>
	</md-card-content>
</md-card>
<md-card class="tajetaConfig">
	<md-card-content>
		<h2 class="md-title">Solicita Biin Cloud Analytics</h2>
		<p>La solución perfecta en la nube para análisis de información de tu empresa.</p>
		<md-button ng-href="User/registro" class="md-primary md-raised">Registra tu empresa</md-button>
	</md-card-content>
</md-card>
</section>