<section id="pagecontent" layout="row" layout-sm="column" flex ng-controller="registroController">
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
		<p>Biin Cloud Analytics necesita conocerte para hacer tu cuenta y darte de alta. Un ejecutivo será notificado de tu solicitud.</p>
		<h2 class="md-title">Cuéntanos de ti</h2>
		<form ng-submit="setRegistro()">
			<md-tabs md-selected="selectedIndex" md-dynamic-height>
				<md-tab label="Identidad">
					<md-input-container >
						<label>Nombre de la empresa (Razón social)</label>
						<input ng-model="registroFormData.nombreEmpresa" type="text" ng-required="true" flex>
					</md-input-container>
					<md-input-container >
						<label>RFC</label>
						<input ng-model="registroFormData.rfc" type="text" ng-required="true" flex>
					</md-input-container>
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Teléfono</label>
							<input ng-model="registroFormData.telefono" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Correo electrónico</label>
							<input ng-model="registroFormData.email" type="text" ng-required="true" flex>
						</md-input-container>
					</div>
					<md-button style="float: right;" class="md-primary md-raised" ng-click="siguiente()">Siguiente</md-button>
				</md-tab>
				<md-tab label="Dirección">
					<md-input-container >
						<label>Calle</label>
						<input ng-model="registroFormData.calle" type="text" ng-required="true" flex>
					</md-input-container>
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Número exterior</label>
							<input ng-model="registroFormData.num_exterior" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Número interior</label>
							<input ng-model="registroFormData.num_interior" type="text" flex>
						</md-input-container>
					</div>
					<md-input-container >
						<label>Colonia</label>
						<input ng-model="registroFormData.colonia" type="text" ng-required="true" flex>
					</md-input-container>
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Municipio/Delegación</label>
							<input ng-model="registroFormData.municipio" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Estado</label>
							<md-select ng-model="registroFormData.estado">
								<md-option ng-repeat="estado in estados" value="{{estado}}">
								{{estado}}
								</md-option>
							</md-select>
						</md-input-container>
					</div>
					<md-input-container >
						<label>Código Postal</label>
						<input ng-model="registroFormData.cp" type="text" ng-required="true" flex>
					</md-input-container>
					<md-button style="float: left;" class="md-primary md-raised" ng-click="anterior()">Anterior</md-button>
					<md-button style="float: right;" class="md-primary md-raised" ng-click="siguiente()">Siguiente</md-button>
				</md-tab>
				<md-tab label="Usuario">
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Nombre</label>
							<input ng-model="registroFormData.nombre" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Apellido Paterno</label>
							<input ng-model="registroFormData.apellido_paterno" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Apellido Materno</label>
							<input ng-model="registroFormData.apellido_materno" type="text" ng-required="true" flex>
						</md-input-container>
					</div>
					<md-input-container >
						<label>Usuario</label>
						<input ng-model="registroFormData.user" type="text" ng-required="true" flex>
					</md-input-container>
					<md-input-container >
						<label>Contraseña</label>
						<input ng-model="registroFormData.password" type="password" ng-required="true" flex>
					</md-input-container>
					<md-button style="float: left;" class="md-primary md-raised" ng-click="anterior()">Anterior</md-button>
					<md-button style="float: right;" class="md-primary md-raised" type="submit">Solicita tu acceso</md-button>
				</md-tab>
			</md-tabs>
		</form>
	</md-card-content>
</md-card>
</section>