<style>
html,body        {height:100%;}
.wrapper         {width:80%;height:100%;margin:0 auto;background:#CCC}
.h_iframe        {position:relative;}
.h_iframe .ratio {display:block;width:100%;height:auto;}
.h_iframe iframe {position:absolute;top:0;left:0;width:100%; height:100%;}
</style>

<section layout="row" layout-sm="column" flex ng-controller="ClienteController">
<!-- <div class="qvobject" style="width: 300px; height: 300px;" data-qvid="KVHSYZ"></div> -->
<md-content class="md-padding" style="height: 100%; width: 100%;">
	<md-tabs md-selected="selectedIndex" md-border-bottom md-autoselect md-dynamic-height>
		<md-tab label="Ventas">
			<div class="wrapper">
				<div class="h_iframe">
					<!-- a transparent image is preferable -->
					<img class="ratio" src="http://placehold.it/16x9"/>
					<iframe ng-src="http://biinqliksense.cloudapp.net/single/?appid=6916355e-28a4-4779-a173-9d2d3ba5c023&sheet=XXraLcN&select=clearall" style="width: 100%; height: 100%;" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</md-tab>
		<md-tab label="Clientes">
			<div class="wrapper">
				<div class="h_iframe">
					<!-- a transparent image is preferable -->
					<img class="ratio" src="http://placehold.it/16x9"/>
					<iframe ng-src="http://biinqliksense.cloudapp.net/single/?appid=6916355e-28a4-4779-a173-9d2d3ba5c023&sheet=zzMzwG&select=clearall" style="width: 100%; height: 100%;" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</md-tab>
		<md-tab label="Producto">
			<div class="wrapper">
				<div class="h_iframe">
					<!-- a transparent image is preferable -->
					<img class="ratio" src="http://placehold.it/16x9"/>
					<iframe ng-src="http://biinqliksense.cloudapp.net/single/?appid=6916355e-28a4-4779-a173-9d2d3ba5c023&sheet=bjtJT&select=clearall" style="width: 100%; height: 100%;" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</md-tab>
	</md-tabs>
</md-content>
</section>