<section id="pagecontent" layout="row" layout-sm="column" flex ng-controller="ClienteController">
<style type="text/css">
	.tajetaConfig {
		width: 100%;
	}
</style>
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
		<h2 class="md-title">Archivo de Excel</h2>
		<p>
			El archivo de Excel contiene toda tu información sobre la operación de tu empresa.
		</p>
		<div>
			<form >
				<span>Logotipo</span>
				<div class="col s12 m12 center-align">
					<md-button md-no-ink class="md-primary md-raised" ngf-select ng-model="cargaFormData.file" accept="application/*">Seleccionar archivo de Excel</md-button>
				</div>
				<md-button md-no-ink ng-show="cargaFormData.file" ng-click="uploadExcel()" class="md-primary md-raised">Cargar archivo</md-button>
			</form>
		</div>
	</md-card-content>
</md-card>
</section>