<section id="pagecontent" layout="row" layout-sm="column" flex ng-controller="ClienteController">
<style type="text/css">
	.tajetaConfig {
		width: 100%;
	}
</style>
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
		<h2 class="md-title">Archivo de Excel</h2>
		<p>
			El archivo de Excel contiene toda tu información sobre la operación de tu empresa.
		</p>
		<div>
			<form >
				<div class="col s12 m12 center-align">
					<md-button class="md-primary md-raised" ngf-select ng-model="cargaFormData.file" accept="application/*">Seleccionar archivo de Excel</md-button>
				</div>
				<md-list ng-show="cargaFormData.file">
			      <md-subheader class="md-no-sticky">Archivo</md-subheader>
			      <md-list-item class="md-3-line">
			        <md-icon style="margin-top: 32px;" md-font-set="material-icons">description</md-icon>
			        <div class="md-list-item-text" layout="column">
			          <h3>{{cargaFormData.file.name}}</h3>
			          <h4>{{cargaFormData.file.size/1024 | number:1}} KB</h4>
			        </div>
			      </md-list-item>
			    </md-list>
				<br>
				<md-button ng-show="cargaFormData.file" ng-click="uploadExcel()" class="md-primary md-raised">Cargar</md-button>
			</form>
		</div>
	</md-card-content>
</md-card>
</section>