<section id="pagecontent" layout="row" flex ng-controller="AdminClientesController">
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
		<md-input-container>
			<label>Buscar Cliente</label>
			<input ng-model="searchCliente" />
		</md-input-container>
		<md-list>
			<md-list-item class="md-3-line" ng-repeat="cliente in clientes | filter:searchCliente">
				<div class="md-list-item-text" layout="column">
					<h3>{{ cliente.nombre }}</h3>
					<h4>{{ cliente.rfc }}</h4>
					<p>{{ cliente.calle }} {{ cliente.num_exterior }} {{ cliente.num_interior }} {{ cliente.num_interior }} {{ cliente.cp }}</p>
				</div>
				<md-button class="md-secondary" ng-click="modClienteDialog($event, $index)">Modificar</md-button>
				<md-divider ></md-divider>
			</md-list-item>
		</md-list>
	</md-card-content>
</md-card>
</div>
</section>