<section id="pagecontent" layout="row" flex ng-controller="AdminUserController">
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
	<h2 class="md-title">Usuarios</h2>
		<md-tabs md-dynamic-height md-border-bottom>
			<md-tab label="Usuarios PYME">
				<md-content class="md-padding">
				<md-input-container>
					<label>Buscar Usuarios PYME</label>
					<input ng-model="searchUsuariosPYME" />
				</md-input-container>
					<md-list>
						<md-list-item class="md-3-line" ng-repeat="usuarioPyme in usuariosPyme | filter:searchUsuariosPYME">
							<div class="md-list-item-text" layout="column">
								<h3>{{ usuarioPyme.nombre }} {{ usuarioPyme.apellido_paterno }} {{ usuarioPyme.apellido_materno }}</h3>
								<h4>{{ usuarioPyme.empresa }}</h4>
							</div>
							<md-button class="md-secondary" ng-click="modPymeDialog($event, $index)">Modificar</md-button>
							<md-divider ></md-divider>
						</md-list-item>
					</md-list>
				</md-content>
			</md-tab>
			<md-tab label="Usuarios Administradores">
				<md-content class="md-padding">
							<md-list>
								<md-list-item class="md-3-line" ng-repeat="usuarioAdmin in usuariosAdmin">
									<div class="md-list-item-text" layout="column">
										<h3>{{ usuarioAdmin.nombre }} {{ usuarioAdmin.apellido_paterno }} {{ usuarioAdmin.apellido_materno }}</h3>
										<h4>Biin Solutions</h4>
									</div>
									<md-button class="md-secondary" ng-click="modAdminDialog($event, $index)">Modificar</md-button>
									<md-divider ></md-divider>
								</md-list-item>
							</md-list>
				</md-content>
			</md-tab>
		</md-tabs>
	</md-card-content>
</md-card>
</div>
</section>