<md-dialog aria-label="Modificación de Cliente"  ng-cloak>
<form>
	<md-toolbar>
		<div class="md-toolbar-tools">
			<h2>Modificación de Cliente</h2>
			<span flex></span>
			<md-button class="md-icon-button" ng-click="cancel()">
				<md-icon aria-label="Close dialog">close</md-icon>
			</md-button>
		</div>
	</md-toolbar>
	<md-dialog-content style="min-width:800px; min-height:300px; ">
		<div class="md-dialog-content">
			<md-tabs md-selected="selectedIndex" md-dynamic-height>
				<md-tab label="Identidad">
					<md-input-container >
						<label>Nombre de la empresa (Razón social)</label>
						<input ng-model="clienteForm.nombre" type="text" ng-required="true" flex>
					</md-input-container>
					<md-input-container >
						<label>RFC</label>
						<input ng-model="clienteForm.rfc" type="text" ng-required="true" flex>
					</md-input-container>
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Teléfono</label>
							<input ng-model="clienteForm.telefono" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Correo electrónico</label>
							<input ng-model="clienteForm.email" type="text" ng-required="true" flex>
						</md-input-container>
					</div>
				</md-tab>
				<md-tab label="Dirección">
					<md-input-container >
						<label>Calle</label>
						<input ng-model="clienteForm.calle" type="text" ng-required="true" flex>
					</md-input-container>
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Número exterior</label>
							<input ng-model="clienteForm.num_exterior" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Número interior</label>
							<input ng-model="clienteForm.num_interior" type="text" flex>
						</md-input-container>
					</div>
					<md-input-container >
						<label>Colonia</label>
						<input ng-model="clienteForm.colonia" type="text" ng-required="true" flex>
					</md-input-container>
					<div layout="row" layout-sm="column">
						<md-input-container >
							<label>Municipio/Delegación</label>
							<input ng-model="clienteForm.municipio" type="text" ng-required="true" flex>
						</md-input-container>
						<md-input-container >
							<label>Estado</label>
							<md-select ng-model="clienteForm.estado">
								<md-option ng-repeat="estado in estados" value="{{estado}}">
								{{estado}}
								</md-option>
							</md-select>
						</md-input-container>
					</div>
					<md-input-container >
						<label>Código Postal</label>
						<input ng-model="clienteForm.cp" type="text" ng-required="true" flex>
					</md-input-container>
				</md-tab>
			</md-tabs>
		</div>
	</md-dialog-content>
	<div class="md-actions" layout="row">
		<span flex></span>
		<md-button ng-click="answer(false)" >
				Cancelar
		</md-button>
		<md-button ng-click="answer(true)" style="margin-right:20px;" >
				Guardar
		</md-button>
	</div>
</form>
</md-dialog>