<style>
.slider {
	width: 100%;
}
</style>
<section layout="row" flex ng-controller="AdminController">
<div ng-cloak class="slider">
	<md-content>
		<md-tabs md-dynamic-height md-border-bottom>
			<md-tab label="Usuarios PYME">
				<md-content class="md-padding">
					<h1 class="md-display-2">Usuarios PYME</h1>
					<md-list>
						<md-subheader class="md-no-sticky">Prueba</md-subheader>
						<md-list-item class="md-3-line" ng-repeat="usuarioPyme in usuariosPyme">
							<div class="md-list-usuarioPyme-text" layout="column">
								<h3>{{ usuarioPyme.nombre }}</h3>
								<h4>{{ usuarioPyme.apellido_paterno }}</h4>
								<p>{{ usuarioPyme.apellido_materno }}</p>
							</div>
						</md-list-item>
					</md-list>
				</md-content>
			</md-tab>
		<md-tab label="Usuarios Administradores">
			<md-content class="md-padding">
				<h1 class="md-display-2">Usuarios Administradores</h1>
						<md-list>
							<md-subheader class="md-no-sticky">Prueba</md-subheader>
							<md-list-item class="md-3-line" ng-repeat="usuarioAdmin in usuariosAdmin">
								<div class="md-list-usuarioAdmin-text" layout="column">
									<h3>{{ usuarioAdmin.nombre }}</h3>
									<h4>{{ usuarioAdmin.apellido_paterno }}</h4>
									<p>{{ usuarioAdmin.apellido_materno }}</p>
								</div>
							</md-list-item>
						</md-list>
			</md-content>
		</md-tab>
	</md-tabs>
	</md-content>
</div>
</section>